version: "3.8"
services:
    server:
        container_name: server
        build:
            context: ./server
        env_file: .env
        environment:
            DATABASE_URL: postgresql://postgres:postgres@postgres:5432/icritic
        restart: unless-stopped
        networks:
            - app-network
        ports:
            - 8080:8080
        depends_on:
            - postgres
    postgres:
        container_name: postgres
        image: postgres:15.2-bullseye
        env_file: .env
        networks:
            - app-network
        ports:
            - 5432:5432
        volumes:
            - postgres:/var/lib/postgresql/data
networks:
    app-network:
        driver: bridge
volumes:
  postgres: {}
